### ISSUE TITLE
Inkscape deprecated export-pdf command line option - inkscape 1.2.2

### ISSUE THREAD

**Issue by mtbrun** [natowi/14-Bit-Circular-Coded-Target#3]
With inkscape 1.2.2, I needed to adapt the code :

In file : create_target_sheets.py/line_103
`subprocess.run(['inkscape', '--export-pdf=' + pdf_filename, svg_filename])`
the command line option `'--export-pdf='` is deprecated and does not work.

Cf inkscape documentation : [https://wiki.inkscape.org/wiki/Using_the_Command_Line#:~:text=available%20here.-,Deprecations%20and%20Replacements,-The%20command%2Dline](url)

The export command line option can be replaced by :
`subprocess.run(['inkscape', '--export-filename=' + pdf_filename, svg_filename])`

The inkscape documention recommends also to replace `--verb` by `actions` for inkscape >= 1.1
With inkscape 1.2.2 the code with `--verb`  is still working : "Eventually all verbs will be replaced by actions. Temporarily, any verb can be used as an action."

I replaced `--verb` by `--actions` and the GUI did not closed automatically. 
I added `--without-gui` in the command line and all worked fine.

Line_99 :
`    subprocess.run(['inkscape', '-g', '--without-gui' , '--select=first',
                    '--actions', 'EditSelectSameObjectType',
                    '--actions', 'StrokeToPath', '--actions', 'SelectionUnion',
                    '--actions', 'FileSave', '--actions', 'FileQuit', svg_filename])`

**Comment by natowi** [comment]
Thank you! You are welcome to create Pull Request :)

**Comment by natowi** [comment]
Thank you, I updated the code accordingly
